// Build data-patch.js from the BookStack markdown export.
// Run:  node build-patch.js
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, 'bookstack-export', 'truth-base-export');

// id → markdown file path (relative to ROOT)
const map = {
  1:  '01-standards/iguide-drafting-standard-policies.md',
  2:  '01-standards/rms-residential-measurement-standard.md',
  7:  '02-software-basics/room-types-residential.md',
  10: '02-software-basics/windows.md',
  15: '04-autodraft/autodraft-training.md',
  26: '10-site-plans/drafting-detailing.md',
  55: '14-updates/draft-update_document-1-1.md',
};

const patch = {};
for (const [id, rel] of Object.entries(map)) {
  const full = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  patch[id] = full;
  console.log(`id=${id}  ${rel}  -> ${full.length} chars`);
}

const out = `// Auto-generated by build-patch.js — do not edit by hand.
// Restores the full content for the 6 docs that were truncated at 8071 chars
// in the embedded DB. Loaded AFTER the inline DB so we can patch in place.
(function(){
  if (typeof DB === 'undefined' || !Array.isArray(DB)) return;
  const PATCH = ${JSON.stringify(patch, null, 2)};
  let replaced = 0;
  for (const [id, content] of Object.entries(PATCH)) {
    const d = DB.find(x => x.id === parseInt(id, 10));
    if (d && content && content.length > d.content.length) {
      d.content = content;
      replaced++;
    }
  }
  // Bust any memoized formatting for these docs
  if (typeof _contentCache === 'object' && _contentCache) {
    for (const id of Object.keys(PATCH)) {
      delete _contentCache['c' + id];
      delete _contentCache['f' + id];
    }
  }
  if (replaced) console.log('[truth-base] restored full content for', replaced, 'docs');
})();
`;

fs.writeFileSync(path.join(__dirname, 'data-patch.js'), out, 'utf8');
console.log(`\nWrote data-patch.js  (${fs.statSync(path.join(__dirname,'data-patch.js')).size} bytes)`);
