// Build data-patch.js from:
//   1. The BookStack markdown export (for docs truncated in the embedded DB)
//   2. new-docs.json manifest (for wholly new docs not in the embedded DB)
// Run:  node build-patch.js
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, 'bookstack-export', 'truth-base-export');

// id → markdown file path (relative to ROOT) for content patches of existing docs
const patchMap = {
  1:  '01-standards/iguide-drafting-standard-policies.md',
  2:  '01-standards/rms-residential-measurement-standard.md',
  7:  '02-software-basics/room-types-residential.md',
  10: '02-software-basics/windows.md',
  15: '04-autodraft/autodraft-training.md',
  26: '10-site-plans/drafting-detailing.md',
  55: '14-updates/draft-update_document-1-1.md',
};

const patch = {};
for (const [id, rel] of Object.entries(patchMap)) {
  const full = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  patch[id] = full;
  console.log(`patch  id=${id}  ${rel}  -> ${full.length} chars`);
}

// New docs (read metadata + markdown content)
let newDocs = [];
const manifestPath = path.join(__dirname, 'new-docs.json');
if (fs.existsSync(manifestPath)) {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  for (const m of manifest) {
    const content = fs.readFileSync(path.join(__dirname, m.md_path), 'utf8');
    newDocs.push({
      id: m.id,
      shelf: m.shelf,
      book: m.book,
      title: m.title,
      source: m.source,
      content: content && content.trim() ? content : (m.title + '\n\n(Content not yet transcribed — see the source PDF.)'),
    });
    console.log(`new    id=${m.id}  ${m.title}  -> ${content.length} chars, ${m.figure_count} figures`);
  }
}

const out = `// Auto-generated by build-patch.js — do not edit by hand.
// Runtime patches to the embedded DB:
//  - Restores full content for docs truncated at 8071 chars
//  - Appends brand-new docs (ids 56+) that weren't in the original extract
(function(){
  if (typeof DB === 'undefined' || !Array.isArray(DB)) return;

  const PATCH = ${JSON.stringify(patch, null, 2)};
  const NEW_DOCS = ${JSON.stringify(newDocs, null, 2)};

  let replaced = 0;
  for (const [id, content] of Object.entries(PATCH)) {
    const d = DB.find(x => x.id === parseInt(id, 10));
    if (d && content && content.length > d.content.length) {
      d.content = content;
      replaced++;
    }
  }

  let added = 0;
  for (const doc of NEW_DOCS) {
    if (!DB.find(x => x.id === doc.id)) {
      DB.push(doc);
      added++;
    }
  }

  if (typeof _contentCache === 'object' && _contentCache) {
    for (const id of Object.keys(PATCH)) {
      delete _contentCache['c' + id];
      delete _contentCache['f' + id];
    }
  }
  if (added && typeof __refreshIndexes === 'function') __refreshIndexes();
  if (replaced || added) console.log('[truth-base] patched', replaced, 'docs and added', added, 'new docs');
})();
`;

fs.writeFileSync(path.join(__dirname, 'data-patch.js'), out, 'utf8');
console.log(`\nWrote data-patch.js  (${fs.statSync(path.join(__dirname, 'data-patch.js')).size} bytes)`);
